/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iteye_weimingtom_ffmpegwrapper_FFmpegJni */

#ifndef _Included_com_iteye_weimingtom_ffmpegwrapper_FFmpegJni
#define _Included_com_iteye_weimingtom_ffmpegwrapper_FFmpegJni
#ifdef __cplusplus
extern "C" {
#endif
#undef com_iteye_weimingtom_ffmpegwrapper_FFmpegJni_D
#define com_iteye_weimingtom_ffmpegwrapper_FFmpegJni_D 1L
/*
 * Class:     com_iteye_weimingtom_ffmpegwrapper_FFmpegJni
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;ZZ)V
 */
JNIEXPORT void JNICALL Java_com_iteye_weimingtom_ffmpegwrapper_FFmpegJni_init
  (JNIEnv *, jobject, jstring, jstring, jboolean, jboolean);

/*
 * Class:     com_iteye_weimingtom_ffmpegwrapper_FFmpegJni
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iteye_weimingtom_ffmpegwrapper_FFmpegJni_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_iteye_weimingtom_ffmpegwrapper_FFmpegJni
 * Method:    main
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_iteye_weimingtom_ffmpegwrapper_FFmpegJni_main
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_iteye_weimingtom_ffmpegwrapper_FFmpegJni
 * Method:    cancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iteye_weimingtom_ffmpegwrapper_FFmpegJni_cancel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
